In [1]:
import pandas as pd
pd.options.mode.chained_assignment = None
import numpy as np

In [2]:
eps=0.66
alpha= 1/5.8
gamma= 1/5
def equations(S_t,E_t,I_t,R_t,B_t,V_t,W_t):
    global N
    global eps
    global alpha
    global gamma 
    S_t_1 = S_t - ((B_t * S_t * I_t)/N) - (eps * V_t) + W_t
    
    E_t_1 = E_t + ((B_t * S_t * I_t)/N) -(alpha * E_t)
    
    I_t_1 = I_t + (alpha * E_t) - (gamma * I_t)
    
    R_t_1 = R_t + (gamma * I_t) + (eps * V_t) - W_t
    
    return S_t_1, E_t_1, I_t_1, R_t_1

In [3]:
df = pd.read_csv('COVID19_data.csv')
df = df[['Date','Confirmed','Tested','First Dose Administered']]

# Making copy of datafarme
df1= df.copy()

# Adding few empty columns in dataframe
df1["Daily_confirmed"] = ""
df1["Daily_Tested"] = ""
df1["Average_of_7days_Confirmed"] = ""
df1["Average_of_7days_Tested"] = ""
df1["Daily_first_dose"] = ""

# **********************************************************************************************************
# Counting daily confirmed and daily tested cases
for i, rowi in df1.iterrows():
    if(i>0):
        df1["Daily_confirmed"][i]= df1["Confirmed"][i] -df1["Confirmed"][i-1]
        df1["Daily_Tested"][i]= df1["Tested"][i] -df1["Tested"][i-1]
        df1["Daily_first_dose"][i]= df1["First Dose Administered"][i]-df1["First Dose Administered"][i-1]
    else:
        df1["Daily_confirmed"][i]= df1["Confirmed"][i]
        df1["Daily_Tested"][i]=   df1["Tested"][i]
        df1["Daily_first_dose"][i]=   df1["First Dose Administered"][i]
        
# ***********************************************************************************************************
# Running average of last 7 days, for both Daily confirmed and Daily tested.
        
for i, rowi in df1.iterrows():
    count_confirmed=0
    c1=0
    count_Tested=0
    c2=0
    for j in range(i-6,i+1):
        if(j<0):
            c1=0
            c2=0
        else:
            c1=df1["Daily_confirmed"][j]
            c2=df1["Daily_Tested"][j]
        
        count_confirmed=count_confirmed+c1
        count_Tested=count_Tested+c2

    df1["Average_of_7days_Confirmed"][i]=count_confirmed/7
    df1["Average_of_7days_Tested"][i]=count_Tested/7
            
# *************************************************************************************************************
df1= df1[(df1["Date"]>='2021-03-16') & (df1["Date"]<='2021-09-11')]
df1 = df1.reset_index(drop=True)
#df1

In [4]:
# Loss_function(B_t,S_t,E_t,I_t,R_O,CIR_O)

In [5]:
# #Predicting data from march 16th till 31st december using optimized parameters
# def Generating_predictions(B_t,S_t,E_t,I_t,R_O,CIR_O):
#     R_t=R_O
    
#     S_t_list=[]
#     E_t_list=[]
#     I_t_list=[]
#     R_t_list=[]
#     W_t_list=[]
#     V_t_list=[]

#     for i in range(0,290):

#         if(i<=30):
# #             print(i)
#             W_t= R_O/30
#             V_t = df1["Daily_first_dose"][i]
#             W_t_list.append(W_t)
#             V_t_list.append(V_t)
#         elif(i>30 and i<=179):
#             W_t=0
#             V_t = df1["Daily_first_dose"][i]
#             W_t_list.append(W_t)
#             V_t_list.append(V_t)
#         else:
# #             print(len(R_t_list)-179)
#             W_t=R_t_list[len(R_t_list)-180] + eps * V_t_list[len(V_t_list)-180]
            
#             V_t=200000                             #seeting vaccinatio per day as 2 lakhs after 
#             V_t_list.append(V_t)
#             W_t_list.append(W_t)



#         S_t_1, E_t_1, I_t_1, R_t_1 =equations(S_t,E_t,I_t,R_t,B_t,V_t,W_t)

#         S_t_list.append(S_t_1)
#         E_t_list.append(E_t_1)
#         I_t_list.append(I_t_1)
#         R_t_list.append(R_t_1)
        
#         S_t, E_t, I_t, R_t= S_t_1, E_t_1, I_t_1, R_t_1


#     return S_t_list,E_t_list,I_t_list,R_t_list,W_t_list,V_t_list

In [6]:
#Predicting data from march 16th till 20TH september using optimized parameters
def Generating_predictions(B_t,S_t,E_t,I_t,R_O,CIR_O):
    R_t=R_O
    
    S_t_list=[]
    E_t_list=[]
    I_t_list=[]
    R_t_list=[]
    W_t_list=[]
    V_t_list=[]

    for i in range(0,189):

        if(i<=30):
#             print(i)
            W_t= R_O/30
            V_t = df1["Daily_first_dose"][i]
            W_t_list.append(W_t)
            V_t_list.append(V_t)
        elif(i>30 and i<=179):
            W_t=0
            V_t = df1["Daily_first_dose"][i]
            W_t_list.append(W_t)
            V_t_list.append(V_t)
        else:
#             print(len(R_t_list)-179)
            W_t=R_t_list[len(R_t_list)-180] + eps * V_t_list[len(V_t_list)-180]
            
            V_t=200000                             #seeting vaccinatio per day as 2 lakhs after 
            V_t_list.append(V_t)
            W_t_list.append(W_t)



        S_t_1, E_t_1, I_t_1, R_t_1 =equations(S_t,E_t,I_t,R_t,B_t,V_t,W_t)

        S_t_list.append(S_t_1)
        E_t_list.append(E_t_1)
        I_t_list.append(I_t_1)
        R_t_list.append(R_t_1)
        
        S_t, E_t, I_t, R_t= S_t_1, E_t_1, I_t_1, R_t_1


    return S_t_list,E_t_list,I_t_list,R_t_list,W_t_list,V_t_list

In [7]:
#Optimized parameter
N = 70000000
R_O = 0.3601 *N
CIR_O= 15.172 
S_t= 0.6362*N                                #60900000 
E_t=0.0021 *N   #.134 *N                                        #7000000
I_t= 0.0016 *N     #0.01 *N                                    #700000 *2

B = 0.4311

In [12]:
# prediction using beta1
B_t=B
S_t_list,E_t_list,I_t_list,R_t_list,W_t_list,V_t_list= Generating_predictions(B_t,S_t,E_t,I_t,R_O,CIR_O)
data_1 = {'S_t':S_t_list,
                'E_t':E_t_list,
               'I_t':I_t_list,
                 'R_t':R_t_list,

                 }

        # Create DataFrame
df_beta1 = pd.DataFrame(data_1)
# print(S_t_list)
df_beta1

              S_t           E_t           I_t           R_t
0    4.734254e+07  8.911724e+06  2.568276e+06  1.117746e+07
1    4.408484e+07  1.084918e+07  3.591125e+06  1.147485e+07
2    3.987425e+07  1.350190e+07  4.743449e+06  1.188041e+07
3    3.468106e+07  1.657802e+07  6.122672e+06  1.261824e+07
4    2.886458e+07  1.978662e+07  7.756418e+06  1.359238e+07
..            ...           ...           ...           ...
184  4.262790e+07 -1.329445e-05 -6.556229e-06  2.737210e+07
185  5.729300e+07 -1.898739e-05 -7.537129e-06  1.270700e+07
186  7.378233e+07 -2.805155e-05 -9.303391e-06 -3.782328e+06
187  9.222164e+07 -4.282725e-05 -1.227919e-05 -2.222164e+07
188  1.131723e+08 -6.779772e-05 -1.720736e-05 -4.317227e+07

[189 rows x 4 columns]

In [13]:
# prediction using beta2

B_t= (2 * B)/3
S_t_list,E_t_list,I_t_list,R_t_list,W_t_list,V_t_list= Generating_predictions(B_t,S_t,E_t,I_t,R_O,CIR_O)
data_1 = {'S_t':S_t_list,
                'E_t':E_t_list,
               'I_t':I_t_list,
                 'R_t':R_t_list,

                 }

        # Create DataFrame
df_beta2 = pd.DataFrame(data_1)
df_beta2

              S_t           E_t           I_t           R_t
0    4.799588e+07  8.258391e+06  2.568276e+06  1.117746e+07
1    4.586420e+07  9.182466e+06  3.478481e+06  1.147485e+07
2    4.313805e+07  1.063810e+07  4.365969e+06  1.185788e+07
3    3.976149e+07  1.239136e+07  5.326930e+06  1.252022e+07
4    3.597748e+07  1.428933e+07  6.397985e+06  1.333520e+07
..            ...           ...           ...           ...
184  4.241813e+07 -4.129873e-06 -3.518436e-06  2.758187e+07
185  5.655437e+07 -6.260597e-06 -3.526796e-06  1.344563e+07
186  7.210793e+07 -8.980341e-06 -3.900850e-06 -2.107928e+06
187  8.905967e+07 -1.278976e-05 -4.669015e-06 -1.905967e+07
188  1.078369e+08 -1.850503e-05 -5.940344e-06 -3.783689e+07

[189 rows x 4 columns]

In [14]:
# prediction using beta3
B_t= B/2
S_t_list,E_t_list,I_t_list,R_t_list,W_t_list,V_t_list= Generating_predictions(B_t,S_t,E_t,I_t,R_O,CIR_O)
data_1 = {'S_t':S_t_list,
                'E_t':E_t_list,
               'I_t':I_t_list,
                 'R_t':R_t_list,

                 }

        # Create DataFrame
df_beta3 = pd.DataFrame(data_1)
df_beta3

              S_t           E_t           I_t           R_t
0    4.832254e+07  7.931724e+06  2.568276e+06  1.117746e+07
1    4.676587e+07  8.337123e+06  3.422159e+06  1.147485e+07
2    4.479224e+07  9.185977e+06  4.175162e+06  1.184662e+07
3    4.233146e+07  1.027383e+07  4.923919e+06  1.247079e+07
4    3.960419e+07  1.148015e+07  5.710485e+06  1.320518e+07
..            ...           ...           ...           ...
184  4.260895e+07  7.020409e-06  5.463712e-06  2.739105e+07
185  5.647766e+07  9.135751e-06  5.581385e-06  1.352234e+07
186  7.155682e+07  1.206382e-05  6.040238e-06 -1.556822e+06
187  8.774873e+07  1.615842e-05  6.912158e-06 -1.774873e+07
188  1.053978e+08  2.203725e-05  8.315661e-06 -3.539784e+07

[189 rows x 4 columns]

In [15]:
# prediction using beta4
B_t= B/3
S_t_list,E_t_list,I_t_list,R_t_list,W_t_list,V_t_list= Generating_predictions(B_t,S_t,E_t,I_t,R_O,CIR_O)
data_1 = {'S_t':S_t_list,
                'E_t':E_t_list,
               'I_t':I_t_list,
                 'R_t':R_t_list,

                 }

        # Create DataFrame
df_beta4 = pd.DataFrame(data_1)
df_beta4

              S_t           E_t           I_t           R_t
0    4.864921e+07  7.605057e+06  2.568276e+06  1.117746e+07
1    4.767552e+07  7.483789e+06  3.365837e+06  1.147485e+07
2    4.645992e+07  7.721748e+06  3.982978e+06  1.183535e+07
3    4.490841e+07  8.152782e+06  4.517719e+06  1.242109e+07
4    4.322658e+07  8.679354e+06  5.019827e+06  1.307424e+07
..            ...           ...           ...           ...
184  4.470960e+07  4.685316e-05  3.579039e-05  2.529040e+07
185  5.830924e+07  5.401478e-05  3.671044e-05  1.169076e+07
186  7.291224e+07  6.508815e-05  3.868125e-05 -2.912240e+06
187  8.834225e+07  8.072641e-05  4.216709e-05 -1.834225e+07
188  1.048582e+08  1.022855e-04  4.765202e-05 -3.485818e+07

[189 rows x 4 columns]